### ISSUE TITLE
请教Failed to fetch plugin https://github.com/Luomusha/cordova-plugin-sharesdk.git via registry.

### ISSUE THREAD

**Issue by WillLeeBebi** [Luomusha/cordova-plugin-sharesdk#1]
-----------------------环境---------------

C:\Users\Admin\myApp>ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
-----------------------环境--------------------
-------------------------报错：-------------------------
[ERROR] An error occurred while running cordova plugin add https://github.com/Luomusha/cordova-plugin-sharesdk.git
        --sav... (exit code 1):

        You have been opted out of telemetry. To change this, run: cordova telemetry on.
        Error: Failed to fetch plugin https://github.com/Luomusha/cordova-plugin-sharesdk.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
        npm WARN addRemoteGit  git+https://github.com/Luomusha/cordova-plugin-sharesdk.git resetting remote
        C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Luomusha-cordova-plugin-sharesdk-git-16404aed
        because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/Luomusha/cordova-plugin-sharesdk.git
        C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Luomusha-cordova-plugin-sharesdk-git-16404aed:
        Cloning into bare repository
        'C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Luomusha-cordova-plugin-sharesdk-git-16404aed'...
        npm ERR! git clone --template=C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/Luomusha/cordova-plugin-sharesdk.git
        C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Luomusha-cordova-plugin-sharesdk-git-16404aed:
        fatal: Unable to find remote helper for 'https'
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        "https://github.com/Luomusha/cordova-plugin-sharesdk.git" "--save"
        npm ERR! node v6.11.0
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/Luomusha/cordova-plugin-sharesdk.git
        C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Luomusha-cordova-plugin-sharesdk-git-16404aed
        npm ERR! Cloning into bare repository
        'C:\Users\Admin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Luomusha-cordova-plugin-sharesdk-git-16404aed'...
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\Admin\myApp\node_modules\npm-debug.log
-------------------------报错：-------------------------

**Comment by Luomusha** [comment]
抱歉给你造成困扰,没想到有人会用我的插件.当**时可能我在更新,直接推在master上了.**
最近插件除了点问题,ios上出现BUG.我打算更新ios的插件到4
